name: gallery
apiVersion: v2
version: 1.0.0
appVersion: 1.0.0
description: Gallery is a JHipster based monolith application
icon: https://www.jhipster.tech/images/logo/logo-jhipster-drink-coffee.svg
keywords:
- spring
- angular
- react
- JHipster
- gallery
home: https://www.jhipster.tech/
sources:
- https://github.com/jhipster/generator-jhipster.git
maintainers:
- name: Team JHipster
  email:
dependencies:
    - name: postgresql
      version: 10.9.0
      repository: https://charts.bitnami.com/bitnami
      condition: postgresql.enabled
    - name: redis
      version: 14.8.8
      repository: https://charts.bitnami.com/bitnami
      condition: redis.enabled
    - name: elasticsearch
      version: 7.9.3
      repository: https://helm.elastic.co
      condition: elasticsearch.enabled
